exports.countrys = () => {
    return [
        {code: 'AF', name: 'Afghanistan', city: 'Kabul'},
        {code: 'AL', name: 'Albania', city: 'Tirana'},
        {code: 'DZ', name: 'Algeria', city: 'Algiers'},
        {code: 'AS', name: 'American Samoa', city: ''},
        {code: 'AD', name: 'Andorra', city: 'Andorra la Vella'},
        {code: 'AO', name: 'Angola', city: 'Luanda'},
        {code: 'AI', name: 'Anguilla', city: ''},
        {code: 'AQ', name: 'Antarctica', city: ''},
        {code: 'AG', name: 'Antigua And Barbuda', city: ''},
        {code: 'AR', name: 'Argentina', city: 'Buenos Aires'},
        {code: 'AM', name: 'Armenia', city: 'Yerevan'},
        {code: 'AW', name: 'Aruba', city: ''},
        {code: 'AU', name: 'Australia', city: 'Yerevan'},
        {code: 'AT', name: 'Austria', city: 'Vienna'},
        {code: 'AZ', name: 'Azerbaijan', city: 'Baku'},
        {code: 'BS', name: 'Bahamas', city: 'Nassau'},
        {code: 'BH', name: 'Bahrain', city: 'Manama'},
        {code: 'BD', name: 'Bangladesh', city: 'Dhaka'},
        {code: 'BB', name: 'Barbados', city: 'Bridgetown'},
        {code: 'BY', name: 'Belarus', city: 'Minsk'},
        {code: 'BE', name: 'Belgium', city: 'Brussels'},
        {code: 'BZ', name: 'Belize', city: 'Belmopan'},
        {code: 'BJ', name: 'Benin', city: 'Porto-Novo'},
        {code: 'BM', name: 'Bermuda', city: ''},
        {code: 'BT', name: 'Bhutan', city: 'Thimphu'},
        {code: 'BO', name: 'Bolivia', city: 'La Paz'},
        {code: 'BA', name: 'Bosnia And Herzegovina', city: 'Sarajevo'},
        {code: 'BW', name: 'Botswana', city: 'Gaborone'},
        {code: 'BV', name: 'Bouvet Island', city: ''},
        {code: 'BR', name: 'Brazil', city: 'Brasilia'},
        {code: 'IO', name: 'British Indian Ocean Territory', city: ''},
        {code: 'BN', name: 'Brunei Darussalam', city: 'Bandar Seri Begawan'},
        {code: 'BG', name: 'Bulgaria', city: 'Sofia'},
        {code: 'BF', name: 'Burkina Faso', city: 'Ouagadougou'},
        {code: 'BI', name: 'Burundi', city: 'Bujumbura'},
        {code: 'KH', name: 'Cambodia', city: 'Phnom Penh'},
        {code: 'CM', name: 'Cameroon', city: 'Yaounde'},
        {code: 'CA', name: 'Canada', city: 'Ottawa'},
        {code: 'CV', name: 'Cape Verde', city: 'Praia'},
        {code: 'KY', name: 'Cayman Islands', city: ''},
        {code: 'CF', name: 'Central African Republic', city: 'Bangui'},
        {code: 'TD', name: 'Chad', city: 'N\'Djamena'},
        {code: 'CL', name: 'Chile', city: 'Santiago'},
        {code: 'CN', name: 'China', city: 'Beijing'},
        {code: 'CX', name: 'Christmas Island', city: ''},
        {code: 'CC', name: 'Cocos (keeling) Islands', city: ''},
        {code: 'CO', name: 'Colombia', city: 'Bogotá'},
        {code: 'KM', name: 'Comoros', city: 'Moroni'},
        {code: 'CG', name: 'Congo', city: 'Kinshasa'},
        {code: 'CD', name: 'Congo, The Democratic Republic Of The', city: 'Kinshasa'},
        {code: 'CK', name: 'Cook Islands', city: ''},
        {code: 'CR', name: 'Costa Rica', city: '	San Jose'},
        {code: 'CI', name: 'Cote D\'ivoire', city: 'Yamoussoukro'},
        {code: 'HR', name: 'Croatia', city: 'Zagreb'},
        {code: 'CU', name: 'Cuba', city: 'Havana'},
        {code: 'CY', name: 'Cyprus', city: 'Nicosia'},
        {code: 'CZ', name: 'Czech Republic', city: 'Prague'},
        {code: 'DK', name: 'Denmark', city: 'Copenhagen'},
        {code: 'DJ', name: 'Djibouti', city: 'Djibouti'},
        {code: 'DM', name: 'Dominica', city: 'Roseau'},
        {code: 'DO', name: 'Dominican Republic', city: 'Santo Domingo'},
        {code: 'TP', name: 'East Timor', city: ''},
        {code: 'EC', name: 'Ecuador', city: 'Quito'},
        {code: 'EG', name: 'Egypt', city: 'Cairo'},
        {code: 'SV', name: 'El Salvador', city: 'San Salvador'},
        {code: 'GQ', name: 'Equatorial Guinea', city: 'Oyala'},
        {code: 'ER', name: 'Eritrea', city: 'Asmara'},
        {code: 'EE', name: 'Estonia', city: 'Tallinn'},
        {code: 'ET', name: 'Ethiopia', city: 'Addis Ababa'},
        {code: 'FK', name: 'Falkland Islands (malvinas)', city: ''},
        {code: 'FO', name: 'Faroe Islands', city: ''},
        {code: 'FJ', name: 'Fiji', city: 'Suva'},
        {code: 'FI', name: 'Finland', city: 'Helsinki'},
        {code: 'FR', name: 'France', city: 'Paris'},
        {code: 'GF', name: 'French Guiana', city: ''},
        {code: 'PF', name: 'French Polynesia', city: ''},
        {code: 'TF', name: 'French Southern Territories', city: ''},
        {code: 'GA', name: 'Gabon', city: 'Libreville'},
        {code: 'GM', name: 'Gambia', city: 'Banjul'},
        {code: 'GE', name: 'Georgia', city: 'Tbilisi'},
        {code: 'DE', name: 'Germany', city: 'Berlin'},
        {code: 'GH', name: 'Ghana', city: 'Accra'},
        {code: 'GI', name: 'Gibraltar', city: ''},
        {code: 'GR', name: 'Greece', city: 'Athens'},
        {code: 'GL', name: 'Greenland', city: ''},
        {code: 'GD', name: 'Grenada', city: 'Saint George\'s'},
        {code: 'GP', name: 'Guadeloupe', city: ''},
        {code: 'GU', name: 'Guam', city: ''},
        {code: 'GT', name: 'Guatemala', city: 'Guatemala City'},
        {code: 'GN', name: 'Guinea', city: 'Conakry'},
        {code: 'GW', name: 'Guinea-bissau', city: 'Bissau'},
        {code: 'GY', name: 'Guyana', city: 'Georgetown'},
        {code: 'HT', name: 'Haiti', city: 'Port-au-Prince'},
        {code: 'HM', name: 'Heard Island And Mcdonald Islands', city: ''},
        {code: 'VA', name: 'Holy See (vatican City State)', city: ''},
        {code: 'HN', name: 'Honduras', city: 'Tegucigalpa'},
        {code: 'HK', name: 'Hong Kong', city: ''},
        {code: 'HU', name: 'Hungary', city: 'Budapest'},
        {code: 'IS', name: 'Iceland', city: 'Reykjavik'},
        {code: 'IN', name: 'India', city: 'New Delhi'},
        {code: 'ID', name: 'Indonesia', city: 'Jakarta'},
        {code: 'IR', name: 'Iran', city: 'Tehran'},
        {code: 'IQ', name: 'Iraq', city: 'Baghdad'},
        {code: 'IE', name: 'Ireland', city: 'Dublin'},
        {code: 'IL', name: 'Israel', city: 'Jerusalem'},
        {code: 'IT', name: 'Italy', city: 'Rome'},
        {code: 'JM', name: 'Jamaica', city: 'Kingston'},
        {code: 'JP', name: 'Japan', city: 'Tokyo'},
        {code: 'JO', name: 'Jordan', city: 'Amman'},
        {code: 'KZ', name: 'Kazakstan', city: 'Astana'},
        {code: 'KE', name: 'Kenya', city: 'Nairobi'},
        {code: 'KI', name: 'Kiribati', city: 'Tarawa'},
        {code: 'KP', name: 'Korea, Democratic People\'s Republic Of', city: ''},
        {code: 'KR', name: 'Korea, Republic Of', city: ''},
        {code: 'KV', name: 'Kosovo', city: 'Pristina'},
        {code: 'KW', name: 'Kuwait', city: 'Kuwait City'},
        {code: 'KG', name: 'Kyrgyzstan', city: 'Bishkek'},
        {code: 'LA', name: 'Lao', city: 'Vientiane'},
        {code: 'LV', name: 'Latvia', city: 'Riga'},
        {code: 'LB', name: 'Lebanon', city: 'Beirut'},
        {code: 'LS', name: 'Lesotho', city: 'Maseru'},
        {code: 'LR', name: 'Liberia', city: 'Monrovia'},
        {code: 'LY', name: 'Libya', city: 'Tripoli'},
        {code: 'LI', name: 'Liechtenstein', city: 'Vaduz'},
        {code: 'LT', name: 'Lithuania', city: 'Vilnius'},
        {code: 'LU', name: 'Luxembourg', city: 'Luxembourg'},
        {code: 'MO', name: 'Macau', city: ''},
        {code: 'MK', name: 'Macedonia', city: 'Skopje'},
        {code: 'MG', name: 'Madagascar', city: 'Antananarivo'},
        {code: 'MW', name: 'Malawi', city: 'Lilongwe'},
        {code: 'MY', name: 'Malaysia', city: 'Kuala Lumpur'},
        {code: 'MV', name: 'Maldives', city: 'Male'},
        {code: 'ML', name: 'Mali', city: 'Bamako'},
        {code: 'MT', name: 'Malta', city: 'Valletta'},
        {code: 'MH', name: 'Marshall Islands', city: 'Majuro'},
        {code: 'MQ', name: 'Martinique', city: ''},
        {code: 'MR', name: 'Mauritania', city: 'Nouakchott'},
        {code: 'MU', name: 'Mauritius', city: 'Port Louis'},
        {code: 'YT', name: 'Mayotte', city: ''},
        {code: 'MX', name: 'Mexico', city: 'Mexico City'},
        {code: 'FM', name: 'Micronesia', city: 'Palikir'},
        {code: 'MD', name: 'Moldova', city: 'Chisinau'},
        {code: 'MC', name: 'Monaco', city: 'Monaco'},
        {code: 'MN', name: 'Mongolia', city: 'Ulaanbaatar'},
        {code: 'MS', name: 'Montserrat', city: ''},
        {code: 'ME', name: 'Montenegro', city: 'Podgorica'},
        {code: 'MA', name: 'Morocco', city: 'Rabat'},
        {code: 'MZ', name: 'Mozambique', city: 'Maputo'},
        {code: 'MM', name: 'Myanmar', city: 'Naypyidaw'},
        {code: 'NA', name: 'Namibia', city: 'Windhoek'},
        {code: 'NR', name: 'Nauru', city: 'Yaren District'},
        {code: 'NP', name: 'Nepal', city: 'Kathmandu'},
        {code: 'NL', name: 'Netherlands', city: 'Amsterdam'},
        {code: 'AN', name: 'Netherlands Antilles', city: ''},
        {code: 'NC', name: 'New Caledonia', city: ''},
        {code: 'NZ', name: 'New Zealand', city: 'Wellington'},
        {code: 'NI', name: 'Nicaragua', city: 'Managua'},
        {code: 'NE', name: 'Niger', city: 'Niamey'},
        {code: 'NG', name: 'Nigeria', city: 'Abuja'},
        {code: 'NU', name: 'Niue', city: ''},
        {code: 'NF', name: 'Norfolk Island', city: ''},
        {code: 'MP', name: 'Northern Mariana Islands', city: ''},
        {code: 'NO', name: 'Norway', city: 'Oslo'},
        {code: 'OM', name: 'Oman', city: 'Muscat'},
        {code: 'PK', name: 'Pakistan', city: 'Islamabad'},
        {code: 'PW', name: 'Palau', city: 'Ngerulmud'},
        {code: 'PS', name: 'Palestine', city: 'Jerusalem'},
        {code: 'PA', name: 'Panama', city: 'Panama City'},
        {code: 'PG', name: 'Papua New Guinea', city: 'Port Moresby'},
        {code: 'PY', name: 'Paraguay', city: 'Asunción'},
        {code: 'PE', name: 'Peru', city: 'Lima'},
        {code: 'PH', name: 'Philippines', city: 'Manila'},
        {code: 'PN', name: 'Pitcairn', city: ''},
        {code: 'PL', name: 'Poland', city: 'Warsaw'},
        {code: 'PT', name: 'Portugal', city: 'Lisbon'},
        {code: 'PR', name: 'Puerto Rico', city: ''},
        {code: 'QA', name: 'Qatar', city: 'Doha'},
        {code: 'RE', name: 'Reunion', city: ''},
        {code: 'RO', name: 'Romania', city: 'Bucharest'},
        {code: 'RU', name: 'Russia', city: 'Moscow'},
        {code: 'RW', name: 'Rwanda', city: 'Kigali'},
        {code: 'SH', name: 'Saint Helena', city: ''},
        {code: 'KN', name: 'Saint Kitts And Nevis', city: 'Basseterre'},
        {code: 'LC', name: 'Saint Lucia', city: 'Castries'},
        {code: 'PM', name: 'Saint Pierre And Miquelon', city: ''},
        {code: 'VC', name: 'Saint Vincent And The Grenadines', city: 'Kingstown'},
        {code: 'WS', name: 'Samoa', city: 'Apia'},
        {code: 'SM', name: 'San Marino', city: 'San Marino'},
        {code: 'ST', name: 'Sao Tome And Principe', city: 'São Tomé'},
        {code: 'SA', name: 'Saudi Arabia', city: 'Riyadh'},
        {code: 'SN', name: 'Senegal', city: 'Dakar'},
        {code: 'RS', name: 'Serbia', city: 'Belgrade'},
        {code: 'SC', name: 'Seychelles', city: 'Victoria'},
        {code: 'SL', name: 'Sierra Leone', city: 'Freetown'},
        {code: 'SG', name: 'Singapore', city: 'Singapore'},
        {code: 'SK', name: 'Slovakia', city: 'Bratislava'},
        {code: 'SI', name: 'Slovenia', city: 'Ljubljana'},
        {code: 'SB', name: 'Solomon Islands', city: 'Honiara'},
        {code: 'SO', name: 'Somalia', city: 'Mogadishu'},
        {code: 'ZA', name: 'South Africa', city: 'Pretoria'},
        {code: 'GS', name: 'South Georgia And The South Sandwich Islands', city: ''},
        {code: 'ES', name: 'Spain', city: 'Madrid'},
        {code: 'LK', name: 'Sri Lanka', city: 'Sri Jayawardenepura Kotte'},
        {code: 'SD', name: 'Sudan', city: 'Khartoum'},
        {code: 'SR', name: 'Suriname', city: 'Paramaribo'},
        {code: 'SJ', name: 'Svalbard And Jan Mayen', city: ''},
        {code: 'SZ', name: 'Swaziland', city: ''},
        {code: 'SE', name: 'Sweden', city: 'Stockholm'},
        {code: 'CH', name: 'Switzerland', city: 'Bern'},
        {code: 'SY', name: 'Syria', city: 'Damascus'},
        {code: 'TW', name: 'Taiwan', city: 'Taipei'},
        {code: 'TJ', name: 'Tajikistan', city: 'Dushanbe'},
        {code: 'TZ', name: 'Tanzania', city: 'Dodoma'},
        {code: 'TH', name: 'Thailand', city: 'Bangkok'},
        {code: 'TG', name: 'Togo', city: 'Lomé'},
        {code: 'TK', name: 'Tokelau', city: ''},
        {code: 'TO', name: 'Tonga', city: 'Nukuʻalofa'},
        {code: 'TT', name: 'Trinidad And Tobago', city: 'Port of Spain'},
        {code: 'TN', name: 'Tunisia', city: 'Tunis'},
        {code: 'TR', name: 'Turkey', city: 'Ankara'},
        {code: 'TM', name: 'Turkmenistan', city: 'Ashgabat'},
        {code: 'TC', name: 'Turks And Caicos Islands', city: ''},
        {code: 'TV', name: 'Tuvalu', city: 'Funafuti'},
        {code: 'UG', name: 'Uganda', city: 'Kampala'},
        {code: 'UA', name: 'Ukraine', city: 'Kyiv'},
        {code: 'AE', name: 'United Arab Emirates', city: 'Abu Dhabi'},
        {code: 'GB', name: 'United Kingdom', city: 'London'},
        {code: 'US', name: 'United States', city: 'Washington, D.C.'},
        {code: 'UM', name: 'United States Minor Outlying Islands', city: ''},
        {code: 'UY', name: 'Uruguay', city: 'Montevideo'},
        {code: 'UZ', name: 'Uzbekistan', city: 'Tashkent'},
        {code: 'VU', name: 'Vanuatu', city: 'Port Vila'},
        {code: 'VE', name: 'Venezuela', city: 'Caracas'},
        {code: 'VN', name: 'Vietnam', city: 'Hanoi'},
        {code: 'VG', name: 'Virgin Islands, British', city: ''},
        {code: 'VI', name: 'Virgin Islands, U.s.', city: ''},
        {code: 'WF', name: 'Wallis And Futuna', city: ''},
        {code: 'EH', name: 'Western Sahara', city: ''},
        {code: 'YE', name: 'Yemen', city: 'Sana\'a'},
        {code: 'ZM', name: 'Zambia', city: 'Lusaka'},
        {code: 'ZW', name: 'Zimbabwe', city: 'Harare'},
    ]
}