env:
  browser: true
  node: true
  commonjs: true
  es6: true
parser: '@typescript-eslint/parser'
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent: ["error", 2]
